INHERIT: base.yml
nav:
  - 'BarRaider - Documentation':
    - 'index.md' # Hidden in the menu, accessed when clicking "Plugin FAQs"
    - 'General Issues': 'faqs/general/index.md'
    - 'How can I help?': 'faqs/general/helping.md'
    - 'Plugins by BarRaider': 'faqs/general/plugins.md'
    - 'Compatibility Chart': 'faqs/general/compatibility.md'
    - 'API Ninja': 'faqs/api-ninja/index.md'
    - 'Battery':
      - 'CORSAIR iCue': 'faqs/battery/icue.md'
      - 'Logitech G HUB': 'faqs/battery/ghub.md'
    - 'OBS Tools':
      - 'Getting Started': 'faqs/obs-tools/getting-started.md'
      - 'Available Actions': 'faqs/obs-tools/actions.md'
      - 'Troubleshooting': 'faqs/obs-tools/troubleshooting.md'
    - 'SoundPad': 'faqs/soundpad/index.md'
    - 'Spotify':
      - 'Getting started': 'faqs/spotify/getting-started.md'
      - 'Troubleshooting': 'faqs/spotify/troubleshooting.md'
      - 'Playlist URI' : 'faqs/spotify/playlist-uri.md'
    - 'Stream Counter':
      - 'Getting started': 'faqs/stream-counter/getting-started.md'
      - 'Troubleshooting': 'faqs/stream-counter/troubleshooting.md'
    - 'SuperMacro':
      - 'Getting started': 'faqs/supermacro/getting-started.md'
      - 'Advanced Settings explained': 'faqs/supermacro/advanced-settings.md'
      - 'Available Actions': 'faqs/supermacro/actions.md'
      - 'Usage Examples': 'faqs/supermacro/examples.md'
      - 'Commands': 'faqs/supermacro/commands.md'
      - 'Functions': 'faqs/supermacro/functions.md'
      - 'Loops': 'faqs/supermacro/loops.md'
      - 'Variables': 'faqs/supermacro/variables.md'
    - 'Twitch Tools':
      - 'Troubleshooting': 'faqs/twitch-tools/troubleshooting.md'
      #- 'Usage Examples': 'faqs/twitch-tools/examples.md' BLANK PAGE
    - 'VoiceMeeter':
      - 'Getting Started': 'faqs/voicemeeter/getting-started.md'
      - 'Available Actions': 'faqs/voicemeeter/actions.md'
      - 'Usage Examples': 'faqs/voicemeeter/examples.md'
      - 'Advanced Fields': 'faqs/voicemeeter/fields.md'
    - 'Windows Mover & Resizer':
      - 'Getting Started': 'faqs/win-mover-resizer/getting-started.md'
      - 'Troubleshooting': 'faqs/win-mover-resizer/troubleshooting.md'
    - 'World Time': 'faqs/world-time/index.md'
  - Discord: http://discord.barraider.com
site_url: https://docs.barraider.com/
extra:
  analytics: 
    provider: google
    property: G-9RJJJJCXFB
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeUSvro9-zwsVDRnCDvAuIBzaAkKnw-3c_DgMnrzfwV6gNd-g/viewform?entry.757033088={url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    cookies:
      analytics: Google Analytics
      github: GitHub
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2022-2023 BarRaider â€“
  <a href="#__consent">Change cookie settings</a>
  